# Generated by Django 3.0.5 on 2020-04-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20200408_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('score', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
