# Generated by Django 3.0.5 on 2020-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_forfait_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
